### ISSUE TITLE
Ask for translating DiscoverMeteor to Vietnamese

### ISSUE THREAD

**Issue by phuongnq** [DiscoverMeteor/DiscoverMeteor_vi#1]
@SachaG
Hi my name is Phuong. I am Vietnamese and a developer.
Right now I am working on a project which is using Meteor. 
I found that Meteor is very useful framework and would like to spread it out to more Vietnamese developers. So it would be very nice if I could join the project to translate to Vietnamese.
For that reason, could you please accept me to join the GitHub team as well as translate "Discover Meteor" to Vietnamese?

**Comment by aladine** [comment]
Hi @phuongnq , interesting. Glad that if you want to offer some help.
Could you guys @SachaG , @tmeasday and @rgoomar,  approve Phuong's request?

**Comment by SachaG** [comment]
Done :)

**Comment by phuongnq** [comment]
thanks to @SachaG and @aladine!
