### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by phuongnq** [DiscoverMeteor/DiscoverMeteor_vi#2]
@aladine can you tell me how to deploy latest source code to http://vi.discovermeteor.com/ ?

**Comment by aladine** [comment]
@phuongnq
Actually I don't know also. I only notice it is auto updated frequently every few days.

**Comment by phuongnq** [comment]
@aladine Thanks for the information. Anyway, I am reviewing whole project. Please feel free to change anything you think should be change :)
